### ISSUE TITLE
Misbehaving on macOS

### ISSUE THREAD

**Issue by itwysgsl** [MicroBitcoinOrg/RainforestPython#1]
For some unknown reason this module works incorrectly on macOS. It fails to run [rotl64](https://github.com/MicroBitcoinOrg/RainforestPython/blob/master/rainforestmodule.c#L473-L479 ) function correctly. Please, consider running test.py before using this module.
It works correctly on other systems like Linux as separate C program on macOS.

**Comment by wtarreau** [comment]
Now pretty sure it's the same problem as fixed in #18.

**Comment by itwysgsl** [comment]
Thanks @wtarreau, this issue is fixed in here https://github.com/MicroBitcoinOrg/RainforestPython/commit/3de0b9731880792d8ad08396f13e479e63fdb8a1 :)
